package qcfcs_toys.probability_game_01;

import qcfcs_math.Complex;
import qcfcs_math.ComplexMatrix;
import qcfcs_math.ComplexVector;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 * This class implements the GUI for the probability game. It was generated by the Intellij Idea GUI designer. The
 * GUI form is located in ProbabilityGame01GUI.form.
 * Created by reesede on 2/19/2017.
 * @author David E. Reese
 * @version 3.1.1
 * @since 3.1.1
 */

// Copyright 2017 David E. Reese
//
// This file is part of QCfCS_java.
//
// QCfCS_java is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// QCfCS_java is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with QCfCS_java.  If not, see <http://www.gnu.org/licenses/>.
//
// History:
//      20170219    D.E. Reese          Creation (Programming Drill 3.1.1)
//      20170228    D.E. Reese          Added createUIComponents(). Changed JTable elements to
//                                      ProbabilityGameMatrixTable classes.
//      20170301    D.E. Reese          Initialize numStatesTextField. Added PropertyChangeListener to
//                                      numStatesTextField.
//      20170307    D.E. Reese          Added code to numStatesTextField.PropertyChangeListener() to change the
//                                      number of states and change the sizes of the tables appropriately. Initially,
//                                      disable the execute button until the start button is clicked. Added
//                                      executeGame(). Added gameType.
//      20170308    D.E. Reese          Added code in executeGame() to perform the boolean game.

public class ProbabilityGame01GUI
{
    /**
     * Title of window.
     */
    private static final String title = "Probabilty Game 01";

    /**
     * Horizontal location of top left of window.
     */
    private static final int xLoc = 200;

    /**
     * Vertical location of top left of window.
     */
    private static final int yLoc = 200;

    /**
     * Width of window.
     */
    private static final int width = 1000;

    /**
     * Height of window.
     */
    private static final int height = 600;

    /**
     * Initial number of states in the game.
     */
    private static final int initialNumberOfStates = 5;

    /**
     * Number of states.
     */
    private int numStates;

    /**
     * Type of the game (same as the type of the transitionMatrixTable).
     */
    private int gameType;

    /**
     * Number of iterations run in game.
     */
    private int numIterations;

    /**
     * Matrix containing transitions.
     */
    private ComplexMatrix transitionMatrix;

    /**
     * Vector containing state.
     */
    private ComplexVector stateVector;

    private JFrame mainFrame;
    private JPanel panel1;
    private JPanel gameTypePanel;
    private JPanel controlPanel;
    private JRadioButton booleanGameButton;
    private JRadioButton realGameButton;
    private JRadioButton complexGameButton;
    private JButton startButton;
    private JPanel mainPanel;
    private JLabel iterationCountLabel;
    private JButton executeButton;
    private JLabel numStateLabel;
    private JFormattedTextField numStatesTextField;
    private JScrollPane mainScrollPane;
    private JPanel gamePanel;
    private JPanel matrixPanel;
    private JPanel statePanel;
    private JButton quitButton;
    private JLabel transitionMatrixLabel;
    private JLabel stateVectorLabel;
    private ProbabilityGameMatrixTable transitionMatrixTable;
    private ProbabilityGameMatrixTable stateVectorTable;
    private ButtonGroup gameTypeButtonGroup;

    public ProbabilityGame01GUI()
    {
        // Set the transition matrix and state vector to null. These will be set to non-null values the first
        // time the execute button is clicked.

        transitionMatrix = null;
        stateVector = null;

        // Set up main frame.

        initializeMainFrame();

        // Create the game type radio button group.

        initializeGameTypeButtonGroup();

        // Set up the number of states in the editable text field.

        numStatesTextField.setPreferredSize(new Dimension(50, numStatesTextField.getPreferredSize().height));
        numStatesTextField.setHorizontalAlignment(JFormattedTextField.CENTER);
        numStatesTextField.setText(Integer.toString(initialNumberOfStates));
        numStates = initialNumberOfStates;

        // Initialize the number of iterations.

        numIterations = 0;
        iterationCountLabel.setText("Iteration Count = " + numIterations);

        // Disable the execute button until the start button is clicked.

        executeButton.setEnabled(false);

        // Create listeners.

        booleanGameButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                gameType = ProbabilityGameMatrixTable.TABLE_TYPE_BOOLEAN;
            }
        });

        realGameButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                gameType = ProbabilityGameMatrixTable.TABLE_TYPE_REAL;
            }
        });

        complexGameButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                gameType = ProbabilityGameMatrixTable.TABLE_TYPE_COMPLEX;
            }
        });

        quitButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                System.exit(0);
            }
        });

        startButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                // Enable the game matrices.

                transitionMatrixTable.setEnabled(true);
                stateVectorTable.setEnabled(true);

                // Disable the game type buttons.

                booleanGameButton.setEnabled(false);
                realGameButton.setEnabled(false);
                complexGameButton.setEnabled(false);

                // Disable the start button itself.

                startButton.setEnabled(false);

                // Enable the execute button.

                executeButton.setEnabled(true);

                // Disable the number of states text field.

                numStatesTextField.setEnabled(false);

                // If the game type is boolean, set the state vector to integer.

                if(transitionMatrixTable.getTableType() == stateVectorTable.TABLE_TYPE_BOOLEAN)
                {
                    stateVectorTable.setTableType(stateVectorTable.TABLE_TYPE_INTEGER);
                }
            }
        });

        numStatesTextField.addPropertyChangeListener(new PropertyChangeListener()
        {
            @Override
            public void propertyChange(PropertyChangeEvent propertyChangeEvent)
            {
                // Get the changed text.

                String theText = numStatesTextField.getText();

                // Parse the text containing the new number of states. If it is not an unsigned integer, then
                // set the text back to the current number of states and return.

                int newNumStates;
                try
                {
                    newNumStates = Integer.parseUnsignedInt(theText);
                }
                catch(NumberFormatException e)
                {
                    numStatesTextField.setText(new Integer(numStates).toString());
                    return;
                }

                // If the new number of states is 0 or the same as the existing number of states, set the text back
                // to the current number of states (there must be at least 1 state) and return.

                if ((newNumStates == 0) || (newNumStates == numStates))
                {
                    numStatesTextField.setText(new Integer(numStates).toString());
                    return;
                }

                // Set the number of states to the new value.

                numStates = newNumStates;
                transitionMatrixTable.resizeTable(numStates,numStates);
                stateVectorTable.resizeTable(numStates,1);
            }
        });

        executeButton.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent actionEvent)
            {
                // Disable the tables so that they can not be edited.

                transitionMatrixTable.setEnabled(false);
                stateVectorTable.setEnabled(false);

                // If the transitionMatrix and stateVector are null, initialize them. If an exception occurs,
                // display a message and exit from the program.

                if((transitionMatrix == null) || (stateVector == null))
                {
                    try
                    {
                        createGameMatrices();
                    }
                    catch (Exception e)
                    {
                        System.out.println("Could not create matrices.");
                        System.exit(-1);
                    }
                }

                // Run an iteration of the game.

                executeGame();
            }
        });

        // Make the window visible.

        mainFrame.pack();
        mainFrame.setVisible(true);
    }

    /**
     * This method initializes the frame for the program GUI.
     */
    private void initializeMainFrame ()
    {
        mainFrame = new JFrame();
        mainFrame.setSize(width, height);
        mainFrame.setLocation(xLoc,yLoc);
        mainFrame.setResizable(true);
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mainFrame.setContentPane(panel1);
    }

    /**
     * This method initializes the game type radio button group.
     */
    private void initializeGameTypeButtonGroup()
    {
        gameTypeButtonGroup = new ButtonGroup();
        gameTypeButtonGroup.add(booleanGameButton);
        gameTypeButtonGroup.add(realGameButton);
        gameTypeButtonGroup.add(complexGameButton);
        booleanGameButton.setSelected(true);
        realGameButton.setSelected(false);
        complexGameButton.setSelected(false);

        // Delete these lines when different types of games are implements.

        realGameButton.setEnabled(false);       // Delete when the real number game is implemented.
        complexGameButton.setEnabled(false);    // Delete when the complex number game is implemented.

        // Set the initial game type to boolean.

        gameType = ProbabilityGameMatrixTable.TABLE_TYPE_BOOLEAN;
    }

    /**
     * This method initializes components from the GUI form.
     */
    private void createUIComponents()
    {
        transitionMatrixTable = new ProbabilityGameMatrixTable(ProbabilityGameMatrixTable.TABLE_TYPE_BOOLEAN,
                initialNumberOfStates,initialNumberOfStates);

        stateVectorTable = new ProbabilityGameMatrixTable(ProbabilityGameMatrixTable.TABLE_TYPE_INTEGER,
                initialNumberOfStates,1);
    }

    /**
     * This method creates the transitionMatrix and stateVector from the information in the corresponding table.
     * @throws Exception    Thrown if numStates <= 0.
     */
    private void createGameMatrices() throws Exception
    {
        // Throw an exception if the number of states is invalid.

        if(numStates <= 0) throw new Exception("numStates <= 0.");

        // Create a new transition matrix if needed.

        if(transitionMatrix == null)
        {
            // Create a new complex square matrix containing the number of states.

            transitionMatrix = new ComplexMatrix(numStates,numStates);

            // Copy the complex values from the GUI table into the transition matrix.

            for(int i = 0; i < numStates; i++)
                for(int j = 0; j < numStates; j++)
                    transitionMatrix.set(i,j,Complex.parseComplex((String)transitionMatrixTable.getValueAt(i,j)));
        }

        // Create a new state vector if needed.

        if(stateVector == null)
        {
            // Create a new complex vector with a number of rows equal to the number of states.

            stateVector = new ComplexVector(numStates);

            // Copy the complex values from the GUI table into the state vector.

            for(int i = 0; i < numStates; i++)
                stateVector.set(i,Complex.parseComplex((String)stateVectorTable.getValueAt(i,0)));
        }
    }

    /**
     * This method executes the game, based on the type of game.
     */
    private void executeGame()
    {
        // Generate a new state vector by multiplying the transition table by the current state vector.

        stateVector = ComplexVector.convertComplexMatrixToVector(ComplexMatrix.multiply(transitionMatrix,stateVector));

        // Process the new state vector based on the type of game.

        switch(gameType)
        {
            case ProbabilityGameMatrixTable.TABLE_TYPE_BOOLEAN:
                for(int i = 0; i < numStates; i++)
                {
                    int theValue = (int)stateVector.get(i).getReal();
                    stateVectorTable.setValueAt((new Integer(theValue)).toString(),i,0);
                }
                break;
        }

        // Increment the number of iterations.

        numIterations++;
        iterationCountLabel.setText("Iteration Count = " + numIterations);
    }
}
